version: '3'
services:
  nginx-php:
    image: croensch/amzn-nginx:stable-php
    build:
      dockerfile: ./resources/docker/nginx-php/Dockerfile
      context: ./
    volumes:
      - ./public:/var/www/public
    ports:
      - 8080:80
    networks:
      - src
  php-fpm:
    build:
      dockerfile: ./resources/docker/php-fpm/Dockerfile
      context: ./
    volumes:
      - ./:/var/www
    networks:
      - src
networks:
  src:
    driver: bridge
