apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.18.0 (06a2e56)
  creationTimestamp: null
  labels:
    io.kompose.service: php-fpm
  name: php-fpm
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: php-fpm
    spec:
      containers:
      - image: php-fpm
        name: php-fpm
        resources: {}
        volumeMounts:
        - mountPath: /var/www
          name: php-fpm-claim0
      restartPolicy: Always
      volumes:
      - name: php-fpm-claim0
        persistentVolumeClaim:
          claimName: php-fpm-claim0
status: {}
